#!/usr/bin/env python3
# encoding=utf-8
# vim: set filetype=python
from appyratus.utils import SysUtils

from {{ project.context.project.name|snake }}.api import cli
from {{ project.context.project.name|snake }}.env import {{ project.context.project.name|camel }}Environment

env = {{ project.context.project.name|camel }}Environment()


def main():
    """
    Main execution for {{ project.context.project.name|title }}
    """
    cli.manifest.load(path=env.manifest_filepath).process()
    cli.start()


if __name__ == "__main__":
    SysUtils.safe_main(main, debug_level=1)
