#!/usr/bin/env python3
# encoding=utf-8
# vim: set filetype=python
from os.path import join, dirname

from appyratus.cli import safe_main

from {{ project.context.project.name|snake }}.api import cli
from {{ project.context.project.name|snake }}.env import {{ project.context.project.name|camel }}Environment

env = {{ project.context.project.name|camel }}Environment()


def main():
    """
    Main execution for {{ project.context.project.name|title }}
    """
    cli.bootstrap(manifest_filepath=env.manifest_filepath)
    cli.start()


if __name__ == "__main__":
    safe_main(main, debug_level=1)
