#!/usr/bin/env python3
# encoding=utf-8
# vim: set filetype=python
from os.path import join, dirname

from appyratus.cli import safe_main

from {{ project.context.project.name|snake }}.api import cli


def main():
    """
    Main execution for {{ project.context.project.name|title }}
    """
    cli.bootstrap(manifest_filepath=join(dirname(__file__), '../manifest.yml'))
    cli.start()


if __name__ == "__main__":
    safe_main(main, debug_level=1)
