---
- {{ chart.name|dash }}/:
  - README.md
  - Chart.yaml
  - values.yaml
  - .helmignore
  - "templates/":
    - NOTES.txt
    - _helpers.tpl
    - deployment.yaml
    - ingress.yaml
    - service.yaml
...
